[nixpacks]
version = "1.20.0"

[nixpacks.setup]
python310 = true
gcc = true

[nixpacks.install]
command = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[nixpacks.start]
command = "python gestaoEquipe.py"
